version: '3.8'

services:
  api:
    image: api:latest # Make sure you have built this image
    container_name: menuportal-api
    restart: always
    env_file:
      - ./.env # Docker Compose will load the .env file
    ports:
      - "3005:3005"
    networks:
      - services-network
    depends_on: # This makes the api wait for postgres to be healthy
      - postgres

  postgres:
    image: postgres:17.5
    container_name: menuportal-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret-password
      POSTGRES_DB: menuportal
      TZ: "Europe/Budapest"
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services-network
    # Add the command to pass PostgreSQL configuration parameters
    command: >
      postgres
      -c shared_buffers=8GB
      -c work_mem=64MB
      -c maintenance_work_mem=512MB
      -c wal_buffers=16MB
      -c checkpoint_timeout=15min
      -c max_wal_size=16GB
      -c effective_cache_size=24GB
      -c log_min_duration_statement=50

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    restart: always
    ports:
      - "3001:3000"
    networks:
      - services-network


volumes:
  postgres_data:

networks:
  services-network:
    driver: bridge