/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSchedulerRouteRouteImport } from './routes/_authenticated/scheduler/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSchedulerIndexRouteImport } from './routes/_authenticated/scheduler/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDishManagerIndexRouteImport } from './routes/_authenticated/dish-manager/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsRestaurantRouteImport } from './routes/_authenticated/settings/restaurant'
import { Route as AuthenticatedSettingsPricesRouteImport } from './routes/_authenticated/settings/prices'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsBusinessHoursRouteImport } from './routes/_authenticated/settings/business-hours'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSchedulerTemplatesRouteImport } from './routes/_authenticated/scheduler/templates'
import { Route as AuthenticatedSchedulerScheduledPostsRouteImport } from './routes/_authenticated/scheduler/scheduled-posts'
import { Route as AuthenticatedSchedulerPendingPostsRouteImport } from './routes/_authenticated/scheduler/pending-posts'
import { Route as AuthenticatedSchedulerHistoryRouteImport } from './routes/_authenticated/scheduler/history'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/clerk/(auth)',
  path: '/clerk/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulerRouteRoute =
  AuthenticatedSchedulerRouteRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchedulerIndexRoute =
  AuthenticatedSchedulerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchedulerRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDishManagerIndexRoute =
  AuthenticatedDishManagerIndexRouteImport.update({
    id: '/dish-manager/',
    path: '/dish-manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsRestaurantRoute =
  AuthenticatedSettingsRestaurantRouteImport.update({
    id: '/restaurant',
    path: '/restaurant',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPricesRoute =
  AuthenticatedSettingsPricesRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBusinessHoursRoute =
  AuthenticatedSettingsBusinessHoursRouteImport.update({
    id: '/business-hours',
    path: '/business-hours',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchedulerTemplatesRoute =
  AuthenticatedSchedulerTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedSchedulerRouteRoute,
  } as any)
const AuthenticatedSchedulerScheduledPostsRoute =
  AuthenticatedSchedulerScheduledPostsRouteImport.update({
    id: '/scheduled-posts',
    path: '/scheduled-posts',
    getParentRoute: () => AuthenticatedSchedulerRouteRoute,
  } as any)
const AuthenticatedSchedulerPendingPostsRoute =
  AuthenticatedSchedulerPendingPostsRouteImport.update({
    id: '/pending-posts',
    path: '/pending-posts',
    getParentRoute: () => AuthenticatedSchedulerRouteRoute,
  } as any)
const AuthenticatedSchedulerHistoryRoute =
  AuthenticatedSchedulerHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedSchedulerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/scheduler': typeof AuthenticatedSchedulerRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/scheduler/history': typeof AuthenticatedSchedulerHistoryRoute
  '/scheduler/pending-posts': typeof AuthenticatedSchedulerPendingPostsRoute
  '/scheduler/scheduled-posts': typeof AuthenticatedSchedulerScheduledPostsRoute
  '/scheduler/templates': typeof AuthenticatedSchedulerTemplatesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/business-hours': typeof AuthenticatedSettingsBusinessHoursRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/prices': typeof AuthenticatedSettingsPricesRoute
  '/settings/restaurant': typeof AuthenticatedSettingsRestaurantRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dish-manager': typeof AuthenticatedDishManagerIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/scheduler/': typeof AuthenticatedSchedulerIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/scheduler/history': typeof AuthenticatedSchedulerHistoryRoute
  '/scheduler/pending-posts': typeof AuthenticatedSchedulerPendingPostsRoute
  '/scheduler/scheduled-posts': typeof AuthenticatedSchedulerScheduledPostsRoute
  '/scheduler/templates': typeof AuthenticatedSchedulerTemplatesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/business-hours': typeof AuthenticatedSettingsBusinessHoursRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/prices': typeof AuthenticatedSettingsPricesRoute
  '/settings/restaurant': typeof AuthenticatedSettingsRestaurantRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dish-manager': typeof AuthenticatedDishManagerIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/scheduler': typeof AuthenticatedSchedulerIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/_authenticated/scheduler': typeof AuthenticatedSchedulerRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/scheduler/history': typeof AuthenticatedSchedulerHistoryRoute
  '/_authenticated/scheduler/pending-posts': typeof AuthenticatedSchedulerPendingPostsRoute
  '/_authenticated/scheduler/scheduled-posts': typeof AuthenticatedSchedulerScheduledPostsRoute
  '/_authenticated/scheduler/templates': typeof AuthenticatedSchedulerTemplatesRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/business-hours': typeof AuthenticatedSettingsBusinessHoursRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/prices': typeof AuthenticatedSettingsPricesRoute
  '/_authenticated/settings/restaurant': typeof AuthenticatedSettingsRestaurantRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dish-manager/': typeof AuthenticatedDishManagerIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/scheduler/': typeof AuthenticatedSchedulerIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/scheduler'
    | '/settings'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/scheduler/history'
    | '/scheduler/pending-posts'
    | '/scheduler/scheduled-posts'
    | '/scheduler/templates'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/business-hours'
    | '/settings/integrations'
    | '/settings/prices'
    | '/settings/restaurant'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/dashboard'
    | '/dish-manager'
    | '/help-center'
    | '/scheduler/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/scheduler/history'
    | '/scheduler/pending-posts'
    | '/scheduler/scheduled-posts'
    | '/scheduler/templates'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/business-hours'
    | '/settings/integrations'
    | '/settings/prices'
    | '/settings/restaurant'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/dashboard'
    | '/dish-manager'
    | '/help-center'
    | '/scheduler'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/_authenticated/scheduler'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/scheduler/history'
    | '/_authenticated/scheduler/pending-posts'
    | '/_authenticated/scheduler/scheduled-posts'
    | '/_authenticated/scheduler/templates'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/business-hours'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/prices'
    | '/_authenticated/settings/restaurant'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dish-manager/'
    | '/_authenticated/help-center/'
    | '/_authenticated/scheduler/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduler': {
      id: '/_authenticated/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AuthenticatedSchedulerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/scheduler/': {
      id: '/_authenticated/scheduler/'
      path: '/'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof AuthenticatedSchedulerIndexRouteImport
      parentRoute: typeof AuthenticatedSchedulerRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dish-manager/': {
      id: '/_authenticated/dish-manager/'
      path: '/dish-manager'
      fullPath: '/dish-manager'
      preLoaderRoute: typeof AuthenticatedDishManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/restaurant': {
      id: '/_authenticated/settings/restaurant'
      path: '/restaurant'
      fullPath: '/settings/restaurant'
      preLoaderRoute: typeof AuthenticatedSettingsRestaurantRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/prices': {
      id: '/_authenticated/settings/prices'
      path: '/prices'
      fullPath: '/settings/prices'
      preLoaderRoute: typeof AuthenticatedSettingsPricesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/business-hours': {
      id: '/_authenticated/settings/business-hours'
      path: '/business-hours'
      fullPath: '/settings/business-hours'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessHoursRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/scheduler/templates': {
      id: '/_authenticated/scheduler/templates'
      path: '/templates'
      fullPath: '/scheduler/templates'
      preLoaderRoute: typeof AuthenticatedSchedulerTemplatesRouteImport
      parentRoute: typeof AuthenticatedSchedulerRouteRoute
    }
    '/_authenticated/scheduler/scheduled-posts': {
      id: '/_authenticated/scheduler/scheduled-posts'
      path: '/scheduled-posts'
      fullPath: '/scheduler/scheduled-posts'
      preLoaderRoute: typeof AuthenticatedSchedulerScheduledPostsRouteImport
      parentRoute: typeof AuthenticatedSchedulerRouteRoute
    }
    '/_authenticated/scheduler/pending-posts': {
      id: '/_authenticated/scheduler/pending-posts'
      path: '/pending-posts'
      fullPath: '/scheduler/pending-posts'
      preLoaderRoute: typeof AuthenticatedSchedulerPendingPostsRouteImport
      parentRoute: typeof AuthenticatedSchedulerRouteRoute
    }
    '/_authenticated/scheduler/history': {
      id: '/_authenticated/scheduler/history'
      path: '/history'
      fullPath: '/scheduler/history'
      preLoaderRoute: typeof AuthenticatedSchedulerHistoryRouteImport
      parentRoute: typeof AuthenticatedSchedulerRouteRoute
    }
  }
}

interface AuthenticatedSchedulerRouteRouteChildren {
  AuthenticatedSchedulerHistoryRoute: typeof AuthenticatedSchedulerHistoryRoute
  AuthenticatedSchedulerPendingPostsRoute: typeof AuthenticatedSchedulerPendingPostsRoute
  AuthenticatedSchedulerScheduledPostsRoute: typeof AuthenticatedSchedulerScheduledPostsRoute
  AuthenticatedSchedulerTemplatesRoute: typeof AuthenticatedSchedulerTemplatesRoute
  AuthenticatedSchedulerIndexRoute: typeof AuthenticatedSchedulerIndexRoute
}

const AuthenticatedSchedulerRouteRouteChildren: AuthenticatedSchedulerRouteRouteChildren =
  {
    AuthenticatedSchedulerHistoryRoute: AuthenticatedSchedulerHistoryRoute,
    AuthenticatedSchedulerPendingPostsRoute:
      AuthenticatedSchedulerPendingPostsRoute,
    AuthenticatedSchedulerScheduledPostsRoute:
      AuthenticatedSchedulerScheduledPostsRoute,
    AuthenticatedSchedulerTemplatesRoute: AuthenticatedSchedulerTemplatesRoute,
    AuthenticatedSchedulerIndexRoute: AuthenticatedSchedulerIndexRoute,
  }

const AuthenticatedSchedulerRouteRouteWithChildren =
  AuthenticatedSchedulerRouteRoute._addFileChildren(
    AuthenticatedSchedulerRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBusinessHoursRoute: typeof AuthenticatedSettingsBusinessHoursRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsPricesRoute: typeof AuthenticatedSettingsPricesRoute
  AuthenticatedSettingsRestaurantRoute: typeof AuthenticatedSettingsRestaurantRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsBusinessHoursRoute:
      AuthenticatedSettingsBusinessHoursRoute,
    AuthenticatedSettingsIntegrationsRoute:
      AuthenticatedSettingsIntegrationsRoute,
    AuthenticatedSettingsPricesRoute: AuthenticatedSettingsPricesRoute,
    AuthenticatedSettingsRestaurantRoute: AuthenticatedSettingsRestaurantRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSchedulerRouteRoute: typeof AuthenticatedSchedulerRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDishManagerIndexRoute: typeof AuthenticatedDishManagerIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSchedulerRouteRoute:
    AuthenticatedSchedulerRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDishManagerIndexRoute: AuthenticatedDishManagerIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
