/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { BaseDishTypeResponseDtoDishTypeValue } from './base-dish-type-response-dto-dish-type-value';

export interface BaseDishTypeResponseDto {
  /** The unique identifier of the dish type */
  dishTypeId: number;
  /** The name of the dish type */
  name: string;
  /** The type value of the dish */
  dishTypeValue: BaseDishTypeResponseDtoDishTypeValue;
}
