/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * The type value of the dish
 */
export type BaseDishTypeResponseDtoDishTypeValue =
  (typeof BaseDishTypeResponseDtoDishTypeValue)[keyof typeof BaseDishTypeResponseDtoDishTypeValue];

 
export const BaseDishTypeResponseDtoDishTypeValue = {
  SOUP: 'SOUP',
  MEAT_SOUP: 'MEAT_SOUP',
  MAIN_DISH: 'MAIN_DISH',
  SIDE_DISH: 'SIDE_DISH',
  SALAD: 'SALAD',
  VEGETABLE_STEW: 'VEGETABLE_STEW',
  DESSERT: 'DESSERT',
  DRINK: 'DRINK',
  KIDS_MENU: 'KIDS_MENU',
  VEGETARIAN: 'VEGETARIAN',
  VEGAN: 'VEGAN',
  GLUTEN_FREE: 'GLUTEN_FREE',
  FISH: 'FISH',
  PASTA: 'PASTA',
  GRILLED: 'GRILLED',
  BREAKFAST: 'BREAKFAST',
  DAILY_MENU: 'DAILY_MENU',
} as const;
