/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Day of the week.
 */
export type BusinessHourResponseDtoDayOfWeek =
  (typeof BusinessHourResponseDtoDayOfWeek)[keyof typeof BusinessHourResponseDtoDayOfWeek];

 
export const BusinessHourResponseDtoDayOfWeek = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;
