/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { BusinessHourResponseDtoDayOfWeek } from './business-hour-response-dto-day-of-week';

export interface BusinessHourResponseDto {
  /** The unique identifier for the business hour entry. */
  id: number;
  /** Day of the week. */
  dayOfWeek: BusinessHourResponseDtoDayOfWeek;
  /** Opening time in HH:MM format. */
  openingTime: string;
  /** Closing time in HH:MM format. */
  closingTime: string;
}
