/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateOfferDto {
  /**
   * The unique identifier of the dish for this offer
   * @minimum 1
   */
  dishId: number;
  /**
   * The price of the offer in the smallest currency unit (e.g., cents for USD)
   * @minimum 0
   */
  price: number;
  /**
   * The availability date of the offer in YYYY-MM-DD format
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  availability: string;
}
