/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateDishDto {
  /** Name of the dish */
  dishName: string;
  /**
   * ID of the dish type category
   * @minimum 1
   */
  dishTypeId: number;
}
