/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { CreateBusinessHourDto } from './create-business-hour-dto';

export interface CreateBulkBusinessHourDto {
  /** An array of business hour objects to create. */
  businessHours: CreateBusinessHourDto[];
}
