/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the schedule, e.g., WEEKLY.
 */
export type CreateScheduleDtoScheduleType =
  (typeof CreateScheduleDtoScheduleType)[keyof typeof CreateScheduleDtoScheduleType];

 
export const CreateScheduleDtoScheduleType = {
  WEEKLY: 'WEEKLY',
  DAILY: 'DAILY',
} as const;
