/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { CreateBusinessHourDtoDayOfWeek } from './create-business-hour-dto-day-of-week';

export interface CreateBusinessHourDto {
  /** Day of the week */
  dayOfWeek: CreateBusinessHourDtoDayOfWeek;
  /** Opening time of the business in HH:MM format (24h) */
  openingTime: string;
  /** Closing time of the business in HH:MM format (24h) */
  closingTime: string;
}
