/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateHolidayDto {
  /**
   * Name of the holiday
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * The date of the holiday in YYYY-MM-DD format
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  date: string;
}
