/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { CreateScheduleDtoScheduleType } from './create-schedule-dto-schedule-type';
import type { PlatformCreationDto } from './platform-creation-dto';

export interface CreateScheduleDto {
  /** The type of the schedule, e.g., WEEKLY. */
  scheduleType: CreateScheduleDtoScheduleType;
  /** The time of day to post in HH:mm format. */
  postTime: string;
  /**
   * The default message content to use if a platform has no custom text.
   * @maxLength 280
   */
  defaultContentText: string;
  /** Array of platform-specific settings for social media posting. */
  platforms: PlatformCreationDto[];
}
