/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface DayHolidayDto {
  /** Unique identifier for the holiday */
  holidayId: number;
  /** Name of the holiday */
  name: string;
}
