/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { Dish } from './dish';

export interface DayMenuDto {
  /** Unique identifier for the menu */
  menuId: number;
  /** Name of the menu */
  menuName: string;
  /** List of dishes included in this menu */
  dishes: Dish[];
  /** Total price of the menu in Hungarian Forint (HUF) */
  price: number;
}
