/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { Dish } from './dish';

export interface DayOffersDto {
  /** Unique identifier for the offer */
  offerId: number;
  /** Price of the offer in Hungarian Forint (HUF) */
  price: number;
  /** Dish details for this offer */
  dish: Dish;
}
