/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface Dish {
  /**
   * Unique identifier for the dish
   * @nullable
   */
  dishId: number | null;
  /**
   * Name of the dish
   * @nullable
   */
  dishName: string | null;
  /**
   * Type identifier for the dish (1: soup, 2: main course, 3: dessert, etc.)
   * @nullable
   */
  dishTypeId: number | null;
}
