/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface DishResponseDto {
  /** The unique identifier of the dish */
  id: number;
  /** The name of the dish */
  dishName: string;
  /** The ID of the restaurant this dish belongs to */
  restaurantId: number;
  /** The ID of the dish type */
  dishTypeId: number;
}
