/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { DishTypeWithDataResponseDtoDishTypeValue } from './dish-type-with-data-response-dto-dish-type-value';

export interface DishTypeWithDataResponseDto {
  /** The unique identifier of the dish type */
  dishTypeId: number;
  /** The name of the dish type */
  name: string;
  /** The type value of the dish */
  dishTypeValue: DishTypeWithDataResponseDtoDishTypeValue;
  /** The price associated with the dish type for the restaurant */
  price: number;
  /** Indicates if the dish type is active for the restaurant */
  isActive: boolean;
  /** Indicates if the dish type is visible on the menu */
  isOnTheMenu: boolean;
}
