/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { DishResponseDto } from './dish-response-dto';
import type { PageMetaDto } from './page-meta-dto';

export interface DishPaginatedResponseDto {
  /** Array of dishes */
  data: DishResponseDto[];
  /** Pagination metadata */
  meta: PageMetaDto;
}
