/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { DishTypeResponseDtoDishTypeValue } from './dish-type-response-dto-dish-type-value';

export interface DishTypeResponseDto {
  /** The unique identifier of the dish type */
  id: number;
  /** The name of the dish type */
  name: string;
  /** The type value of the dish */
  dishTypeValue: DishTypeResponseDtoDishTypeValue;
}
