/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { DishTypeWithPriceResponseDtoDishTypeValue } from './dish-type-with-price-response-dto-dish-type-value';

export interface DishTypeWithPriceResponseDto {
  /** The unique identifier of the dish type */
  id: number;
  /** The name of the dish type */
  name: string;
  /** The type value of the dish */
  dishTypeValue: DishTypeWithPriceResponseDtoDishTypeValue;
  /** The price associated with the dish type for the restaurant */
  price: number;
}
