/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * The type of schedule.
 */
export type GetScheduleSettingsResponseDtoScheduleType =
  (typeof GetScheduleSettingsResponseDtoScheduleType)[keyof typeof GetScheduleSettingsResponseDtoScheduleType];

 
export const GetScheduleSettingsResponseDtoScheduleType = {
  WEEKLY: 'WEEKLY',
  DAILY: 'DAILY',
} as const;
