/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of schedule (e.g. DAILY, WEEKLY)
 */
export type GetScheduleSettingsResponseDtoScheduleType =
  (typeof GetScheduleSettingsResponseDtoScheduleType)[keyof typeof GetScheduleSettingsResponseDtoScheduleType];

 
export const GetScheduleSettingsResponseDtoScheduleType = {
  WEEKLY: 'WEEKLY',
  DAILY: 'DAILY',
} as const;
