/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type GetDailyMenuFormat =
  (typeof GetDailyMenuFormat)[keyof typeof GetDailyMenuFormat];

 
export const GetDailyMenuFormat = {
  pdf: 'pdf',
  png: 'png',
} as const;
