/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type GetDailyMenuPlatform =
  (typeof GetDailyMenuPlatform)[keyof typeof GetDailyMenuPlatform];

 
export const GetDailyMenuPlatform = {
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  TWITTER: 'TWITTER',
} as const;
