/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { GetPlatformSettingsResponseDto } from './get-platform-settings-response-dto';
import type { GetScheduleSettingsResponseDtoScheduleType } from './get-schedule-settings-response-dto-schedule-type';

export interface GetScheduleSettingsResponseDto {
  /** Unique identifier of the schedule setting */
  id: number;
  /** Type of schedule (e.g. DAILY, WEEKLY) */
  scheduleType: GetScheduleSettingsResponseDtoScheduleType;
  /** Time of day when the post should be published (HH:mm) */
  postTime: string;
  /** Default text for scheduled posts */
  defaultContentText: string;
  /** Whether the schedule is active */
  isActive: boolean;
  /** List of platform-specific settings for this schedule */
  platforms: GetPlatformSettingsResponseDto[];
}
