/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface GetPlatformSettingsResponseDto {
  /** Unique identifier of the platform setting */
  id: number;
  /** ID of the linked social media account */
  socialMediaAccountId: number;
  /**
   * Optional custom content text for this platform
   * @nullable
   */
  contentText?: string | null;
  /** Whether the platform is active */
  isActive: boolean;
}
