/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type GetPaginatedDishesParams = {
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of items per page
   */
  limit?: number;
  /**
   * Filter by dish type ID
   */
  dishTypeId?: number;
  /**
   * Search term for dish name
   */
  search?: string;
};
