/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { GetDailyMenuFormat } from './get-daily-menu-format';
import type { GetDailyMenuPlatform } from './get-daily-menu-platform';

export type GetDailyMenuParams = {
  /**
   * Specify a platform for a custom template. Omit for the default menu.
   */
  platform?: GetDailyMenuPlatform;
  /**
   * The output format. Defaults to 'pdf'.
   */
  format?: GetDailyMenuFormat;
};
