/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { GetWeeklyMenuFormat } from './get-weekly-menu-format';
import type { GetWeeklyMenuPlatform } from './get-weekly-menu-platform';

export type GetWeeklyMenuParams = {
  /**
   * Specify a platform for a custom template. Omit for the default menu.
   */
  platform?: GetWeeklyMenuPlatform;
  /**
   * The output format. Defaults to 'pdf'.
   */
  format?: GetWeeklyMenuFormat;
};
