/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { GetPlatformSettingsResponseDtoContentText } from './get-platform-settings-response-dto-content-text';

export interface GetPlatformSettingsResponseDto {
  /** The unique identifier of the platform settings. */
  id: number;
  /** The ID of the social media account these settings apply to. */
  socialMediaAccountId: number;
  /**
   * The text that will accompany the social media post. Null means use default.
   * @nullable
   */
  contentText: GetPlatformSettingsResponseDtoContentText;
  /** Whether posting to this social media account is active. */
  isActive: boolean;
}
