/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * The text that will accompany the social media post. Null means use default.
 * @nullable
 */
export type GetPlatformSettingsResponseDtoContentText = {
  [key: string]: unknown;
} | null;
