/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type GetWeeklyMenuPlatform =
  (typeof GetWeeklyMenuPlatform)[keyof typeof GetWeeklyMenuPlatform];

 
export const GetWeeklyMenuPlatform = {
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  TWITTER: 'TWITTER',
} as const;
