/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type GetWeeklyMenuFormat =
  (typeof GetWeeklyMenuFormat)[keyof typeof GetWeeklyMenuFormat];

 
export const GetWeeklyMenuFormat = {
  pdf: 'pdf',
  png: 'png',
} as const;
