/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { GetPlatformSettingsResponseDto } from './get-platform-settings-response-dto';
import type { GetScheduleSettingsResponseDtoScheduleType } from './get-schedule-settings-response-dto-schedule-type';

export interface GetScheduleSettingsResponseDto {
  /** The unique identifier of the schedule settings. */
  id: number;
  /** The type of schedule. */
  scheduleType: GetScheduleSettingsResponseDtoScheduleType;
  /** The time of day to post in HH:mm format. */
  postTime: string;
  /** The default message content for posts. */
  defaultContentText: string;
  /** Whether this schedule is globally active. */
  isActive: boolean;
  /** Array of platform-specific settings. */
  platforms: GetPlatformSettingsResponseDto[];
}
