/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface HolidayResponseDto {
  /** Unique identifier of the holiday */
  id: number;
  /** Name of the holiday */
  name: string;
  /** Date of the holiday in YYYY-MM-DD format */
  date: string;
  /** ID of the associated restaurant */
  restaurantId: number;
}
