/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export * from './create-dish-dto';
export * from './create-menu-dto';
export * from './create-offer-dto';
export * from './day-menu-dto';
export * from './day-offers-dto';
export * from './dish';
export * from './dish-paginated-response-dto';
export * from './dish-response-dto';
export * from './dish-type-response-dto';
export * from './dish-type-response-dto-dish-type-value';
export * from './get-daily-menu-format';
export * from './get-daily-menu-params';
export * from './get-daily-menu-platform';
export * from './get-paginated-dishes-params';
export * from './get-platform-settings-response-dto';
export * from './get-platform-settings-response-dto-content-text';
export * from './get-schedule-settings-response-dto';
export * from './get-schedule-settings-response-dto-schedule-type';
export * from './get-weekly-menu-format';
export * from './get-weekly-menu-params';
export * from './get-weekly-menu-platform';
export * from './menu-response-dto';
export * from './offer-response-dto';
export * from './page-meta-dto';
export * from './platform-settings-dto';
export * from './post';
export * from './post-platform';
export * from './post-status';
export * from './render-daily-template-params';
export * from './render-daily-template-platform';
export * from './render-weekly-template-params';
export * from './render-weekly-template-platform';
export * from './restaurant-dto';
export * from './schedule-settings-dto';
export * from './schedule-settings-dto-schedule-type';
export * from './search-dishes-by-name-params';
export * from './social-account-dto';
export * from './social-account-dto-platform';
export * from './social-callback-params';
export * from './social-dto';
export * from './social-dto-platform';
export * from './social-dto-token-expires-at';
export * from './update-activation-dto';
export * from './update-dish-dto';
export * from './update-menu-dto';
export * from './update-offer-dto';
export * from './update-schedule-settings-dto';
export * from './update-schedule-settings-dto-schedule-type';
export * from './user-dto';
export * from './user-dto-with-restaurant';
export * from './user-dto-with-restaurant-restaurant';
export * from './week-menu-day-dto';
export * from './week-menu-response-dto';
export * from './week-menu-response-dto-days';
export * from './week-menu-response-dto-week-status';
