/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export * from './create-dish-dto';
export * from './create-menu-dto';
export * from './create-offer-dto';
export * from './day-menu-dto';
export * from './day-offers-dto';
export * from './dish';
export * from './dish-response-dto';
export * from './menu-response-dto';
export * from './offer-response-dto';
export * from './restaurant-dto';
export * from './search-dishes-by-name-params';
export * from './update-dish-dto';
export * from './update-menu-dto';
export * from './update-offer-dto';
export * from './user-dto';
export * from './user-dto-with-restaurant';
export * from './user-dto-with-restaurant-restaurant';
export * from './week-menu-day-dto';
export * from './week-menu-response-dto';
export * from './week-menu-response-dto-days';
