/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface MenuResponseDto {
  /** The unique identifier of the menu */
  id: number;
  /** Name of the menu */
  menuName: string;
  /** The price of the menu in the smallest currency unit (e.g., cents) */
  price: number;
  /** The availability date of the menu in YYYY-MM-DD format */
  availability: string;
  /** Array of dish IDs included in the menu */
  dishes: number[];
}
