/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface PageMetaDto {
  /** Current page number */
  page: number;
  /** Items per page */
  limit: number;
  /** Total number of items across all pages */
  itemCount: number;
  /** Total number of pages */
  pageCount: number;
  /** Whether a previous page exists */
  hasPreviousPage: boolean;
  /** Whether a next page exists */
  hasNextPage: boolean;
}
