/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface PlatformCreationDto {
  /** The ID of the social media account these settings apply to. */
  socialMediaAccountId: number;
  /** Custom text for this platform. If omitted, the default will be used. */
  contentText?: string;
  /** Whether posting to this social media account is active. */
  isActive: boolean;
}
