/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface PlatformSettingsDto {
  /** The text that will accompany the social media post. */
  contentText: string;
  /** Whether posting to this social media account is active. */
  isActive: boolean;
  /** The ID of the social media account these settings apply to. */
  socialMediaAccountId: number;
}
