/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the post
 */
export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus];

 
export const PostStatus = {
  DRAFT: 'DRAFT',
  PARTIALLY_FAILED: 'PARTIALLY_FAILED',
  SCHEDULED: 'SCHEDULED',
  PUBLISHED: 'PUBLISHED',
  FAILED: 'FAILED',
  PUBLISHING: 'PUBLISHING',
} as const;
