/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { PostPlatform } from './post-platform';
import type { PostScheduleType } from './post-schedule-type';
import type { PostStatus } from './post-status';

export interface Post {
  /** Unique identifier for the post */
  postId: number;
  /** Status of the post */
  status: PostStatus;
  /** Social media platform where the post is published */
  platform: PostPlatform;
  /** Scheduled date and time for the post in ISO 8601 format */
  scheduledAt: string;
  /** Type of schedule for the post */
  scheduleType: PostScheduleType;
}
