/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of schedule for the post
 */
export type PostScheduleType =
  (typeof PostScheduleType)[keyof typeof PostScheduleType];

 
export const PostScheduleType = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
} as const;
