/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type RenderWeeklyTemplatePlatform =
  (typeof RenderWeeklyTemplatePlatform)[keyof typeof RenderWeeklyTemplatePlatform];

 
export const RenderWeeklyTemplatePlatform = {
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  TWITTER: 'TWITTER',
} as const;
