/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { RenderWeeklyTemplatePlatform } from './render-weekly-template-platform';

export type RenderWeeklyTemplateParams = {
  /**
   * Specify a platform for a custom template. Omit for the default menu.
   */
  platform?: RenderWeeklyTemplatePlatform;
};
