/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type RenderDailyTemplatePlatform =
  (typeof RenderDailyTemplatePlatform)[keyof typeof RenderDailyTemplatePlatform];

 
export const RenderDailyTemplatePlatform = {
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  TWITTER: 'TWITTER',
} as const;
