/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { RenderDailyTemplatePlatform } from './render-daily-template-platform';

export type RenderDailyTemplateParams = {
  /**
   * Specify a platform for a custom template. Omit for the default menu.
   */
  platform?: RenderDailyTemplatePlatform;
};
