/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface RestaurantDishTypeSettingDto {
  /** The unique identifier of the dish type. */
  dishTypeId: number;
  /**
   * The price of the dish type in the restaurant.
   * @minimum 0
   */
  price: number;
  /** Whether the dish type is currently active. */
  isActive: boolean;
  /** Whether the dish type is visible on the menu. */
  isOnTheMenu: boolean;
}
