/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface RestaurantDto {
  /** Phone number of the restaurant */
  phoneNumber: string;
  /** Address of the restaurant */
  address: string;
  /**
   * Takeaway price of the restaurant
   * @nullable
   */
  takeawayPrice?: string | null;
  /** Unique identifier of the restaurant */
  id: number;
  /** Name of the restaurant */
  name: string;
}
