/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { PlatformSettingsDto } from './platform-settings-dto';
import type { ScheduleSettingsDtoScheduleType } from './schedule-settings-dto-schedule-type';

export interface ScheduleSettingsDto {
  /** The time of day to post in HH:mm format. */
  postTime: string;
  /**
   * The message content to include in the social media post.
   * @maxLength 280
   */
  defaultContentText: string;
  /** The type of the schedule, e.g., WEEKLY. */
  scheduleType: ScheduleSettingsDtoScheduleType;
  /** Array of platform-specific settings for social media posting. */
  platforms: PlatformSettingsDto[];
}
