/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export type SearchDishesByNameParams = {
  /**
   * Name or partial name of the dish to search for
   */
  name: string;
};
