/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * The social media platform.
 */
export type SocialAccountDtoPlatform =
  (typeof SocialAccountDtoPlatform)[keyof typeof SocialAccountDtoPlatform];

 
export const SocialAccountDtoPlatform = {
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  TWITTER: 'TWITTER',
} as const;
