/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { SocialAccountDtoPlatform } from './social-account-dto-platform';

export interface SocialAccountDto {
  /** The social media platform. */
  platform: SocialAccountDtoPlatform;
  /** Indicates if auto-posting is enabled for this platform. */
  isActive: boolean;
  /** The name of the connected social media account. */
  accountName: string;
}
