/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Token expiration date in ISO format, or null if not set
 * @nullable
 */
export type SocialDtoTokenExpiresAt = { [key: string]: unknown } | null;
