/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { SocialDtoPlatform } from './social-dto-platform';
import type { SocialDtoTokenExpiresAt } from './social-dto-token-expires-at';

export interface SocialDto {
  /** Unique identifier for the social account */
  id: number;
  /** Social media platform */
  platform: SocialDtoPlatform;
  /** Whether the social account is active */
  isActive: boolean;
  /**
   * Token expiration date in ISO format, or null if not set
   * @nullable
   */
  tokenExpiresAt: SocialDtoTokenExpiresAt;
}
