/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Social media platform
 */
export type SocialDtoPlatform =
  (typeof SocialDtoPlatform)[keyof typeof SocialDtoPlatform];

 
export const SocialDtoPlatform = {
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  TWITTER: 'TWITTER',
} as const;
