/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * The day of the week to post the menu.
 */
export type UpdateScheduleSettingsDtoPostDay =
  (typeof UpdateScheduleSettingsDtoPostDay)[keyof typeof UpdateScheduleSettingsDtoPostDay];

 
export const UpdateScheduleSettingsDtoPostDay = {
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  MONDAY: 'MONDAY',
} as const;
