/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Day of the week
 */
export type UpdateBusinessHourDtoDayOfWeek =
  (typeof UpdateBusinessHourDtoDayOfWeek)[keyof typeof UpdateBusinessHourDtoDayOfWeek];

 
export const UpdateBusinessHourDtoDayOfWeek = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;
