/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateScheduleSettingsDtoPostDay } from './update-schedule-settings-dto-post-day';

export interface UpdateScheduleSettingsDto {
  /** Enable or disable the weekly scheduling. */
  enabled: boolean;
  /** The day of the week to post the menu. */
  postDay: UpdateScheduleSettingsDtoPostDay;
  /** The time of day to post in HH:mm format. */
  postTime: string;
  /**
   * The message content to include in the social media post.
   * @maxLength 280
   */
  message: string;
}
