/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { RestaurantDishTypeSettingDto } from './restaurant-dish-type-setting-dto';

export interface UpdateRestaurantDishTypesDto {
  /** The list of dish type settings to update. */
  settings: RestaurantDishTypeSettingDto[];
}
