/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateMenuDto {
  /**
   * Array of dish IDs to include in the menu
   * @minItems 1
   */
  dishes?: number[];
  /**
   * The availability date of the menu in YYYY-MM-DD format
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  availability?: string;
  /**
   * Name of the menu
   * @minLength 1
   * @maxLength 255
   */
  menuName?: string;
  /**
   * The price of the menu in the smallest currency unit (e.g., cents for USD)
   * @minimum 0
   */
  price?: number;
}
