/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateRestaurantSettingDto {
  /** The name of the restaurant. */
  name: string;
  /** The restaurant's contact phone number. */
  phoneNumber: string;
  /** The physical address of the restaurant. */
  address: string;
  /** The price for takeaway orders. */
  takeawayPrice?: number;
  /** The price for menu. */
  menuPrice?: number;
}
