/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateActivationDto {
  /** The desired activation status of the schedule. */
  isActive: boolean;
}
