/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateBusinessHourDtoDayOfWeek } from './update-business-hour-dto-day-of-week';

export interface UpdateBusinessHourDto {
  /** Day of the week */
  dayOfWeek?: UpdateBusinessHourDtoDayOfWeek;
  /** Opening time of the business in HH:MM format (24h) */
  openingTime?: string;
  /** Closing time of the business in HH:MM format (24h) */
  closingTime?: string;
}
