/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateScheduleDto {
  /** The time of day to post in HH:mm format. */
  postTime: string;
  /**
   * The default message content for posts.
   * @maxLength 280
   */
  defaultContentText: string;
  /** A master switch to globally enable or disable this entire schedule. */
  isActive: boolean;
}
