/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UpdatePlatformScheduleDto {
  /**
   * The custom text for this specific platform. Send null to revert to the default text.
   * @nullable
   */
  contentText?: string | null;
  /** Enable or disable posting just for this platform. */
  isActive: boolean;
}
