/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { UserDtoWithRestaurantRestaurant } from './user-dto-with-restaurant-restaurant';

export interface UserDtoWithRestaurant {
  /** Unique identifier of the user */
  id: string;
  /** External ID of the user */
  externalId: string;
  /**
   * Restaurant associated with the user
   * @nullable
   */
  restaurant: UserDtoWithRestaurantRestaurant;
}
