/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
  /** Unique identifier of the user */
  id: string;
  /** External ID of the user */
  externalId: string;
}
