/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { RestaurantDto } from './restaurant-dto';

/**
 * Restaurant associated with the user
 * @nullable
 */
export type UserDtoWithRestaurantRestaurant = RestaurantDto | null;
