/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { DayHolidayDto } from './day-holiday-dto';
import type { DayMenuDto } from './day-menu-dto';
import type { DayOffersDto } from './day-offers-dto';

export interface WeekMenuDayDto {
  /** List of individual dish offers for the day */
  offers: DayOffersDto[];
  /** List of complete menus available for the day */
  menus: DayMenuDto[];
  /** Holiday information for the day, if applicable */
  holiday: DayHolidayDto;
}
