/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the weekly menu
 */
export type WeekMenuResponseDtoWeekStatus =
  (typeof WeekMenuResponseDtoWeekStatus)[keyof typeof WeekMenuResponseDtoWeekStatus];

 
export const WeekMenuResponseDtoWeekStatus = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  PUBLISHED: 'PUBLISHED',
  FAILED: 'FAILED',
} as const;
