/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { Post } from './post';
import type { WeekMenuResponseDtoDays } from './week-menu-response-dto-days';
import type { WeekMenuResponseDtoWeekStatus } from './week-menu-response-dto-week-status';

export interface WeekMenuResponseDto {
  /** Start date of the week in ISO date format (YYYY-MM-DD) */
  weekStart: string;
  /** End date of the week in ISO date format (YYYY-MM-DD) */
  weekEnd: string;
  /** Status of the weekly menu */
  weekStatus: WeekMenuResponseDtoWeekStatus;
  /** List of posts with their status and platform */
  posts: Post[];
  /**
   * Reason for failure if the week menu failed to be published
   * @nullable
   */
  failureReason: string | null;
  /** Indicates if at least one social media account is set up */
  isAccountSetup: boolean;
  /** Daily menu data indexed by date (YYYY-MM-DD format) */
  days: WeekMenuResponseDtoDays;
  /** Indicates if the week menu is empty (no offers or menus) */
  isEmpty: boolean;
  /** Indicates if the week is in the past */
  isPast: boolean;
  /** Indicates if the week is the current week */
  isCurrentWeek: boolean;
  /** Indicates if the week is the planning week */
  isPlanningWeek: boolean;
}
