/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import axios from 'axios';

import type {
  CreateDishDto,
  DishResponseDto,
  SearchDishesByNameParams,
  UpdateDishDto,
} from '.././schemas';

/**
 * @summary Create a new dish
 */
export const createDish = (
  createDishDto: CreateDishDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<DishResponseDto>> => {
  return axios.post(`/api/dish`, createDishDto, options);
};

export const getCreateDishMutationOptions = <
  TError = AxiosError<null | null>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDish>>,
    TError,
    { data: CreateDishDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDish>>,
  TError,
  { data: CreateDishDto },
  TContext
> => {
  const mutationKey = ['createDish'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDish>>,
    { data: CreateDishDto }
  > = props => {
    const { data } = props ?? {};

    return createDish(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDishMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDish>>
>;
export type CreateDishMutationBody = CreateDishDto;
export type CreateDishMutationError = AxiosError<null | null>;

/**
 * @summary Create a new dish
 */
export const useCreateDish = <
  TError = AxiosError<null | null>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createDish>>,
      TError,
      { data: CreateDishDto },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createDish>>,
  TError,
  { data: CreateDishDto },
  TContext
> => {
  const mutationOptions = getCreateDishMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get all dishes
 */
export const getAllDishes = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<DishResponseDto[]>> => {
  return axios.get(`/api/dish`, options);
};

export const getGetAllDishesQueryKey = () => {
  return [`/api/dish`] as const;
};

export const getGetAllDishesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllDishes>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllDishes>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllDishesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllDishes>>> = ({
    signal,
  }) => getAllDishes({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllDishes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllDishesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllDishes>>
>;
export type GetAllDishesQueryError = AxiosError<unknown>;

export function useGetAllDishes<
  TData = Awaited<ReturnType<typeof getAllDishes>>,
  TError = AxiosError<unknown>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllDishes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDishes>>,
          TError,
          Awaited<ReturnType<typeof getAllDishes>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllDishes<
  TData = Awaited<ReturnType<typeof getAllDishes>>,
  TError = AxiosError<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllDishes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDishes>>,
          TError,
          Awaited<ReturnType<typeof getAllDishes>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllDishes<
  TData = Awaited<ReturnType<typeof getAllDishes>>,
  TError = AxiosError<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllDishes>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all dishes
 */

export function useGetAllDishes<
  TData = Awaited<ReturnType<typeof getAllDishes>>,
  TError = AxiosError<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllDishes>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllDishesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Search for dishes by name (fuzzy search)
 */
export const searchDishesByName = (
  params: SearchDishesByNameParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<DishResponseDto[]>> => {
  return axios.get(`/api/dish/search`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getSearchDishesByNameQueryKey = (
  params?: SearchDishesByNameParams
) => {
  return [`/api/dish/search`, ...(params ? [params] : [])] as const;
};

export const getSearchDishesByNameQueryOptions = <
  TData = Awaited<ReturnType<typeof searchDishesByName>>,
  TError = AxiosError<null>
>(
  params: SearchDishesByNameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchDishesByName>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchDishesByNameQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchDishesByName>>
  > = ({ signal }) => searchDishesByName(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchDishesByName>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchDishesByNameQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchDishesByName>>
>;
export type SearchDishesByNameQueryError = AxiosError<null>;

export function useSearchDishesByName<
  TData = Awaited<ReturnType<typeof searchDishesByName>>,
  TError = AxiosError<null>
>(
  params: SearchDishesByNameParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchDishesByName>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchDishesByName>>,
          TError,
          Awaited<ReturnType<typeof searchDishesByName>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchDishesByName<
  TData = Awaited<ReturnType<typeof searchDishesByName>>,
  TError = AxiosError<null>
>(
  params: SearchDishesByNameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchDishesByName>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchDishesByName>>,
          TError,
          Awaited<ReturnType<typeof searchDishesByName>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchDishesByName<
  TData = Awaited<ReturnType<typeof searchDishesByName>>,
  TError = AxiosError<null>
>(
  params: SearchDishesByNameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchDishesByName>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search for dishes by name (fuzzy search)
 */

export function useSearchDishesByName<
  TData = Awaited<ReturnType<typeof searchDishesByName>>,
  TError = AxiosError<null>
>(
  params: SearchDishesByNameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchDishesByName>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchDishesByNameQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a dish by ID
 */
export const getDishById = (
  id: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<DishResponseDto>> => {
  return axios.get(`/api/dish/${id}`, options);
};

export const getGetDishByIdQueryKey = (id?: number) => {
  return [`/api/dish/${id}`] as const;
};

export const getGetDishByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getDishById>>,
  TError = AxiosError<null>
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDishById>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDishByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDishById>>> = ({
    signal,
  }) => getDishById(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDishById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDishByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDishById>>
>;
export type GetDishByIdQueryError = AxiosError<null>;

export function useGetDishById<
  TData = Awaited<ReturnType<typeof getDishById>>,
  TError = AxiosError<null>
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDishById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDishById>>,
          TError,
          Awaited<ReturnType<typeof getDishById>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDishById<
  TData = Awaited<ReturnType<typeof getDishById>>,
  TError = AxiosError<null>
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDishById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDishById>>,
          TError,
          Awaited<ReturnType<typeof getDishById>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDishById<
  TData = Awaited<ReturnType<typeof getDishById>>,
  TError = AxiosError<null>
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDishById>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a dish by ID
 */

export function useGetDishById<
  TData = Awaited<ReturnType<typeof getDishById>>,
  TError = AxiosError<null>
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDishById>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDishByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a dish by ID
 */
export const updateDishById = (
  id: number,
  updateDishDto: UpdateDishDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<DishResponseDto>> => {
  return axios.patch(`/api/dish/${id}`, updateDishDto, options);
};

export const getUpdateDishByIdMutationOptions = <
  TError = AxiosError<null | null>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDishById>>,
    TError,
    { id: number; data: UpdateDishDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDishById>>,
  TError,
  { id: number; data: UpdateDishDto },
  TContext
> => {
  const mutationKey = ['updateDishById'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDishById>>,
    { id: number; data: UpdateDishDto }
  > = props => {
    const { id, data } = props ?? {};

    return updateDishById(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateDishByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDishById>>
>;
export type UpdateDishByIdMutationBody = UpdateDishDto;
export type UpdateDishByIdMutationError = AxiosError<null | null>;

/**
 * @summary Update a dish by ID
 */
export const useUpdateDishById = <
  TError = AxiosError<null | null>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDishById>>,
      TError,
      { id: number; data: UpdateDishDto },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateDishById>>,
  TError,
  { id: number; data: UpdateDishDto },
  TContext
> => {
  const mutationOptions = getUpdateDishByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a dish by ID
 */
export const deleteDishById = (
  id: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<null>> => {
  return axios.delete(`/api/dish/${id}`, options);
};

export const getDeleteDishByIdMutationOptions = <
  TError = AxiosError<null>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDishById>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDishById>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteDishById'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDishById>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return deleteDishById(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDishByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDishById>>
>;

export type DeleteDishByIdMutationError = AxiosError<null>;

/**
 * @summary Delete a dish by ID
 */
export const useDeleteDishById = <
  TError = AxiosError<null>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDishById>>,
      TError,
      { id: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDishById>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteDishByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
